### ISSUE TITLE
Insert Introduction line in About Us 

### ISSUE THREAD

**Issue by shivamkumard107** [D3v3sh5ingh/Androidified#19]
Guys, we have a beautiful problem in the  About Team Activity. The  team members name and profile has been successfully added but I removed the Androidified name and that line "We are a team of passionate learners, powered by innovation, driven by enthusiasm". So try to insert the linen on the top of the Activity. Jisne yeh resolve kar diya usko ek samosa aur coldDrink ki party pakka.

**Comment by D3v3sh5ingh** [comment]
Completed with #27
