### ISSUE TITLE
Add your image @GitHub\Androidified\app\src\main\res\drawable

### ISSUE THREAD

**Issue by D3v3sh5ingh** [D3v3sh5ingh/Androidified#24]
Removing you gandi wali image.for about us section.

**Comment by shivamkumard107** [comment]
Hello All, 
as I am designing the About Us section with Devesh and Mohit I want your facebook LinkedIn and GitHub profile link to add it in the about us section along with a photo(very similar to passport size). Kindly upload your details here in comments.. Thank you : )

**Comment by D3v3sh5ingh** [comment]
Fb Link : fb.com/d3v3sh5ingh
github : github.com/d3v3sh5ingh
Mail : d3v3sh.singh@gmail.com
