### ISSUE TITLE
Making the links of GitHub, Facebook and LinkedIn functional

### ISSUE THREAD

**Issue by MohitR1999** [D3v3sh5ingh/Androidified#36]

**Comment by shivanggarg1998** [comment]
@shivanggarg1998
https://github.com/shivanggarg1998
https://www.facebook.com/profile.php?id=100020423178311
shivanggarg1998@gmail.com

**Comment by hg2199** [comment]
https://github.com/hg2199
https://www.facebook.com/hg2199
harshitgupta.219@gmail.com

**Comment by Sam9905** [comment]
Github : https://github.com/Sam9905
Facebook : https://www.facebook.com/sameep.yadav.3
LinkedIN : https://www.linkedin.com/in/sameep-yadav-0a224b147/
Gmail : Sameepyadav@gmail.com

**Comment by D3v3sh5ingh** [comment]
Fb Link : fb.com/d3v3sh5ingh
github : github.com/d3v3sh5ingh
Mail : d3v3sh.singh@gmail.com

**Comment by yashgautam1221** [comment]
FB link: https://m.facebook.com/yash.gautam.1221
Github: https://github.com/yashgautam1221
Mail -ID: yash.gautam0003@gmail.com
LinkedIn: https://www.linkedin.com/in/yash-gautam-1b136615b/

**Comment by shivamkumard107** [comment]
FB :https://m.facebook.com/shivam.kumar.167?ref=bookmarks
GITHUB : https://github.com/shivamkumard107
GMAIL : shivam.kumard107@gmail.com

**Comment by Vaishalikash** [comment]
Git hub : https://github.com/Vaishalikash
Gmail : kashyapvaishali1998@gmail.com

**Comment by shivamkumard107** [comment]
I think it's time to close this issue?
